spring:
  profiles:
      active: local # default 프로필 설정
      group: # 활성화 프로필과 함께 사용할 프로필 설정
        local:
          - common
#        aws:
#          - common

--- # common, 맨앞에 두지 않으면 현재 프로필 설정 확인 시 common이됨
spring:
  config:
    activate:
      onProfile: common  
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      connection-test-query: select 1
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: false
  servlet:
    multipart:
      max-file-size: 1024KB
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: olenaelim@gmail.com
    password: obtwybsgiwdjahba
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/sql-*.xml

token:
  expiration-time: 86400000
  secret: keyedhashmessageauthenticationcodehashbasedmessageauth

--- # local
spring:
  config:
    activate:
      onProfile: local
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/olenaelim?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
      username: root
      password: 1234

image:
  location: C:/img/
  member-location: C:/img/member/
  read: file:C:/img/

#--- # prd
#spring:
#  config:
#    activate:
#      onProfile: aws
#  datasource:
#    hikari:
#      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/olenaelim?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
#      username: root
#      password: 1234
#
#cloud:
#  aws:
#    credentials:
#      instance-profile: true
#    s3:
#      bucket: olenaelim-image-storage
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
#
#image:
#  location: /home/
#  member-location: /home/member
#  read: https://s3.ap-northeast-2.amazonaws.com/olenaelim-image-storage/
